spring:
  application:
    name: spring-data-jpa-with-spring-boot
  data:
    rest:
      base-path: /api
      page-param-name: sahifa
      limit-param-name: limit
#      max-page-size: 12
#      default-page-size: 2
server:
  port: 9090