spring:
  application:
    name: spring-data-jpa-with-spring-boot
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/spring_data_jpa
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: off