spring:
  config:
    activate:
      on-profile: dev
  task:
    execution:
      pool:
        core-size: 8
        max-size: 20
        keep-alive: 10s
        queue-capacity: 50
      thread-name-prefix: dev-
  h2:
    console:
      enabled: true
      path: /h2-db
  datasource:
    url: 'jdbc:h2:mem:~'
    username: user
    password: 123
    driver-class-name: org.h2.Driver