example:
  string: >
    Hello PDP
    Hello PDP
    Hello PDP
    Hello PDP
    Hello PDP
    Hello PDP
  # | or >
  languages:
    - Java
    - Python
    - Scale
    - Groovy
  languages2: [ Java, Python, Scale, Groovy ]
  numbers: "{ 'one': 1, 'two': 2 }"
  person: { 'id': 1,
            'firstname': Asadbek,
            'lastname': Abdinazarov,
            'age': 20 }
  peoples:
    - id: ${random.int}
      firstname: Asadbek
      lastname: Abdinazarov
      fullname: ${example.person.firstname} ${example.person.lastname}
      age: 20
    - id: ${random.int}
      firstname: Asadbek1
      lastname: Abdinazarov1
      fullname: ${example.person.firstname} | ${example.person.lastname}
      age: 21