spring:
  config:
    activate:
      on-profile: test
  task:
    execution:
      pool:
        core-size: 5
        max-size: 10
        keep-alive: 5s
        queue-capacity: 40
      thread-name-prefix: test-
  datasource:
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
